# Generated by Django 5.2.5 on 2025-10-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='student name')),
                ('email', models.EmailField(max_length=227, verbose_name='student email')),
            ],
        ),
    ]
